### PR TITLE
feat(pkg/*): Set Envoy sidecar log-evel via configMap

### LINKED ISSUE #1232: Set Envoy sidecar log-level via OSM ConfigMap
See `sidecar.go` & search the OSM repo for this issue

### PR DESCRIPTION
**Pull request by tapaskapadia**
Set Envoy sidecar log-level via OSM ConfigMap. Resolve #1232 

Please mark with X for applicable areas.

- [X] New Functionality
- [ ] Documentation
- [ ] Install
- [ ] Control Plane
- [ ] CLI Tool
- [ ] Certificate Management
- [ ] Networking
- [ ] Metrics
- [ ] SMI Policy
- [ ] Security
- [ ] Tests / CI System
- [ ] Other

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?
No

### CODE REVIEW

**Comment by tapaskapadia** [comment]
Here's a small snippet of the validation I did to test the changes are working. 
[osmEnvoyLogLevelWorking.txt](https://github.com/openservicemesh/osm/files/5046572/osmEnvoyLogLevelWorking.txt)

Please let me know if anything needs to be refactored. Thanks!

**Comment by tapaskapadia** [comment]
I forced pushed a commit message amend to change a commit message that did not follow the contributor guidelines.

**Comment by tapaskapadia** [comment]
Updated the PR with some unit test cases in the method_test.go for GetEnvoyLogLevel. I tried to follow the format which I saw in there, but let me know if any changes are needed. 

Not related to this PR but just a heads up on something I noticed, method_test.go is missing unit tests for ZipkinAddress, ZipkinPort, and ZipkinEndpoint.

**Comment by michelleN** [comment]
Thanks @tapaskapadia !

**Comment by draychev** [comment]
This is good stuff!
Thank you @tapaskapadia

**Pull request merged**
