### PR TITLE
Added test for cert manager

### LINKED ISSUE #3437: test: pkg/certificate/providers/tresor/certificate.go - NewCertManager() failures
In `pkg/certificate/providers/tresor/certificate.go`, the unit test coverage can be improved for the NewCertManager() func. See highlighted lines below.

image

Scenarios not covered:
* error creating cert manager for a nil ca

ref #1489

### PR DESCRIPTION
**Pull request by mudit-01**
Added test for cert manager for a nil ca Fixes #3437

Signed-off-by: mudit singh <mudit.singh@india.nec.com>

**Description**:

**Testing done**: yes

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [ ] |
| CI System                  | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [ ] |
| Demo                       | [ ] |
| Documentation              | [ ] |
| Egress                     | [ ] |
| Ingress                    | [ ] |
| Install                    | [ ] |
| Networking                 | [ ] |
| Observability              | [ ] |
| Performance                | [ ] |
| SMI Policy                 | [ ] |
| Security                   | [ ] |
| Sidecar Injection          | [ ] |
| Tests                      | [x ] |
| Upgrade                    | [ ] |
| Other                      | [ ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project?
    -   Did you notify the maintainers and provide attribution?

2. Is this a breaking change?

### CODE REVIEW

**Comment by mudit-01** [comment]
Hi I am not able to figure out why e2e test is failing would appreciate any guidance for the same

**Review by allenlsy — APPROVED** [review]

**Comment by allenlsy** [comment]
@mudit-01 The failure was due to pod not coming up in k8s. I guess this can be happen when Action server does not have enough capacity at that moment. Re-run the jobs later can solve the problem.

**Comment by mudit-01** [comment]
thanks @allenlsy for the review

**Review by ksubrmnn — APPROVED** [review]

**Comment by mudit-01** [comment]
Thanks @ksubrmnn for the review

**Pull request merged**
