### PR TITLE
increase test coverage to look for coverage outside of current package

### PR DESCRIPTION
**Pull request by steeling**
Test coverage, by default, only reports the coverage within the package of the unit test. However many of our tests should be considered integration tests, with tests crossing package boundaries. By applying the coverpkg flag each test will now check coverage against all packages in the `pkg` directory. 

This will likely slow down our unit tests, but our tests suite is largely dominated by e2e tests so this should be negligible

### CODE REVIEW

**Review by keithmattix — APPROVED** [review]

**Comment by steeling** [comment]
i had missed test coverage in ./cmd/... initially, repushed with that change, so let's see what codecov bot reports now

**Comment by keithmattix** [comment]
I'm confused by this [report](https://app.codecov.io/gh/openservicemesh/osm/compare/5013/overview); the unittest delta says -7.25%, but when you dig into the actual coverage changes, there's a net increase....

**Comment by steeling** [comment]
> I'm confused by this [report](https://app.codecov.io/gh/openservicemesh/osm/compare/5013/overview); the unittest delta says -7.25%, but when you dig into the actual coverage changes, there's a net increase.... 

If I had to guess the positive delta's are on files that are still in report.. negative was due to dropping coverage in ./cmd/...

anybody know how to get the report to re-run? @shashankram  @nojnhuh

**Comment by steeling** [comment]
oh wait no that's even worse when including cli... ya idk what that's about

**Comment by steeling** [comment]
> oh wait no that's even worse when including cli... ya idk what that's about

I think it's that each package is now printing coverage of the entire code base, so pkg X coverage in pkg X is 80%, but of the whole codebase is maybe 10%.

Instead of properly tracking all the lines that are covered it's doing this? I'm just going to avoid the headache of reasoning with this and closing it.

**Pull request closed without merging**
