### PR TITLE
cli: move portForwarder to a more generic location

### PR DESCRIPTION
**Pull request by eduser25**
This commit just moves PortForwarder to a more generic/utils
location in the repo.

Testing will require immediate use of port-forwarding; moving
it to a less bloated/more generic package hopes to reduced number
of imports and coupling between users of this feature.

Signed-off-by: Eduard Serra <eduser25@gmail.com>

**Affected area**:

- Other                  [X]

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?
No

### CODE REVIEW

**Review by snehachhabria — DISMISSED** [review]

**Review by nojnhuh — APPROVED** [review]

**Review by draychev — DISMISSED** [review]
This looks great. Thanks for refactoring this.
I wonder if at some future point it would make sense to move it to Kubernetes-specific utils package, since this is not Service Mesh specific.

**Comment by shashankram** [comment]
@eduser25 thanks for the change. It seems to me it would be more appropriate to move this under `pkg/kubernetes`, since the portforwarding implementation is specific to kubernetes.

**Comment by eduser25** [comment]
> @eduser25 thanks for the change. It seems to me it would be more appropriate to move this under `pkg/kubernetes`, since the portforwarding implementation is specific to kubernetes.

agreed, I'll do. I was not 100% convinced when moving that was the right location.
Should it be in it's own package/folder? seems to me small yet container enough that it wouldn't hurt maybe

**Comment by eduser25** [comment]
tests didn't seem to trigger even with a reasonable change... ?

**Review by draychev — APPROVED** [review]

**Review by shashankram — APPROVED** [review]

**Pull request merged**
