### PR TITLE
style(pkg/envoy/route/rbac_test): Alias deckarep/golang-set with mapset

### PR DESCRIPTION
**Pull request by nshankar13**
Signed-off-by: nshankar13 <nshankar@microsoft.com>

**Description**: Convert from set to mapset in rbac_test.go

**Affected area**:

- New Functionality      [ ]
- Documentation          [ ]
- Install                [ ]
- Control Plane          [ ]
- CLI Tool               [ ]
- Certificate Management [ ]
- Networking             [ ]
- Metrics                [ ]
- SMI Policy             [ ]
- Security               [ ]
- Tests                  [ ]
- CI System              [ ]
- Demo                   [ ]
- Performance            [ ]
- Other                  [X]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?

### CODE REVIEW

**Review by snehachhabria — APPROVED** [review]
nit : all the alias PR's could have been combined

**Comment by nshankar13** [comment]
@snehachhabria The issue this resolves suggested using 6 different PRs: https://github.com/openservicemesh/osm/issues/3083

**Comment by shashankram** [comment]
> nit : all the alias PR's could have been combined

+1, I don't think this warrants multiple PRs. Its not that big a change where context will be lost in a single PR.

**Comment by snehachhabria** [comment]
> @snehachhabria The issue this resolves suggested using 6 different PRs: #3083

I don't think its really needed, as the change is the same in all the files and is easy to review

**Comment by draychev** [comment]
@snehachhabria @shashankram I actually requested @nshankar13 split them up.  I personally find it easy to look at the file and know that it is one atomic change - very easy to understand - very easy to approve.

**Review by draychev — APPROVED** [review]

**Comment by shashankram** [comment]
> @snehachhabria @shashankram I actually requested @nshankar13 split them up. I personally find it easy to look at the file and know that it is one atomic change - very easy to understand - very easy to approve.

I understand that might be a personal preference, but for such changes I feel it's better to do it in one shot to reduce the chances of some other change introducing similar changes while multiple small PRs are in flight.

**Pull request merged**
