### PR TITLE
test: Multicluster Gateway's CDS configuration

### PR DESCRIPTION
**Pull request by draychev**
This PR adds a test for the CDS configuration of a Multicluster gateway.

This PR is stacked on #3925

### CODE REVIEW

**Review by snehachhabria — COMMENTED** [review]
I am not sure if now is a good time to add a unit test, the code for CDS in multicluster isn't complete yet and adding a test will just mean more changes once the code is ready.

Could we hold off on this for a bit ?

**Comment by draychev** [comment]
> I am not sure if now is a good time to add a unit test, the code for CDS in multicluster isn't complete yet and adding a test will just mean more changes once the code is ready.
> 
> Could we hold off on this for a bit ?

@snehachhabria No rush at all - this could stay a draft PR until we have CDS ready.  I had it it a branch where I was experimenting. Did not want to lose it or forget about it. I think this could be useful **once CDS is ready**. Will keep it dormant until then if that's ok with you.

**Comment by snehachhabria** [comment]
> @snehachhabria No rush at all - this could stay a draft PR until we have CDS ready. I had it it a branch where I was experimenting. Did not want to lose it or forget about it. I think this could be useful **once CDS is ready**. Will keep it dormant until then if that's ok with you.

Sure, we can definitely add them once we have the pieces figured out

**Comment by draychev** [comment]
@snehachhabria already created tests for this!

**Pull request closed without merging**
