### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by prapakaransp**
Updated latest installation link

**Description**:

Updated the latest installation link.

**Testing done**:

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [ ] |
| CI System                  | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [ ] |
| Demo                       | [ ] |
| Documentation              | [ ] |
| Egress                     | [ ] |
| Ingress                    | [ ] |
| Install                    | [ ] |
| Networking                 | [ ] |
| Observability              | [ ] |
| Performance                | [ ] |
| SMI Policy                 | [ ] |
| Security                   | [ ] |
| Sidecar Injection          | [ ] |
| Tests                      | [ ] |
| Upgrade                    | [ ] |
| Other                      | [ ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project?
    -   Did you notify the maintainers and provide attribution?

2. Is this a breaking change?

### CODE REVIEW

**Review by snehachhabria — APPROVED** [review]

**Review by snehachhabria — APPROVED** [review]
Please follow the instructions here to sign off your commit : https://github.com/openservicemesh/osm/blob/main/CONTRIBUTING.md#sign-your-work

**Review by shashankram — APPROVED** [review]

**Comment by bridgetkromhout** [comment]
Hi, @prapakaransp - please look at https://github.com/openservicemesh/osm/pull/4358/checks?check_run_id=4207388011 to see how to sign the DCO - thanks!

**Comment by mudit-01** [comment]
In my opinion, the links should be generic like https://docs.openservicemesh.io/docs/getting_started/install/ and not version-specific like https://release-v0-11.docs.openservicemesh.io/docs/getting_started/install/
@shashankram @snehachhabria what are your views?

**Comment by snehachhabria** [comment]
stale PR closing

**Pull request closed without merging**
