### PR TITLE
self-nominate steeling as a maintainer

### PR DESCRIPTION
**Pull request by steeling**

### CODE REVIEW

**Comment by allenlsy** [comment]
@steeling can you add me as maintainer in this PR as well?

**Comment by allenlsy** [comment]
Discussed offline. Additional code maintainer will be added in separate PR.

**Comment by nojnhuh** [comment]
+1

**Review by nojnhuh — APPROVED** [review]

**Review by jaellio — APPROVED** [review]
+1

**Review by shashankram — COMMENTED** [review]
+1

@steeling could you rebase this change, and also add your username to the CODEOWNERS file

**Review by keithmattix — APPROVED** [review]
+1

**Comment by trstringer** [comment]
This is good to merge as a majority (5/7) of the existing maintainers are in agreement.

**Pull request merged**
