### PR TITLE
maintainers: transition myself to emeritus status

### PR DESCRIPTION
**Pull request by shashankram**
**Description**:
I no longer have the time to dedicate to this project, so I
am transitioning myself to emeritus status.

Good luck to everyone.

### CODE REVIEW

**Review by keithmattix — APPROVED** [review]

**Comment by keithmattix** [comment]
Thank you for all of your efforts over the years Shashank! OSM would not be where it is without. Good luck in your new endeavors!

**Review by shalier — APPROVED** [review]

**Review by trstringer — APPROVED** [review]
Thank you for all of your contributions, Shashank!

**Comment by draychev** [comment]
@shashankram It really saddens me to see you leave the maintainers list.

Allow me to share with you how much I have enjoyed working with you and the other folks on this project in the past 3 years. I will forever cherish the memories of the pre-pandemic days, when @snehachhabria, you and I walked to each other's desks and discussed service mesh.  The whiteboarding sessions in Sunnyvale were just as epic as the 7th-floor view of Moffett Field. Shashank, your contributions have been monumental! You're tenacious and with an eye on quality, readability and a really high bar for product development. Without your persistence and creativity we wouldn't have been able to get OSM to OSS, CNCF donation, then v1 and private/public/GA launches as a managed product.
And finally - selfishly - I loved learning from you! You're a wonderful human being, amazing engineer, and I really hope I get to write & review code with you again!

**Comment by shashankram** [comment]
> @shashankram It really saddens me to see you leave the maintainers list.
> 
> Allow me to share with you how much I have enjoyed working with you and the other folks on this project in the past 3 years. I will forever cherish the memories of the pre-pandemic days, when @snehachhabria, you and I walked to each other's desks and discussed service mesh. The whiteboarding sessions in Sunnyvale were just as epic as the 7th-floor view of Moffett Field. Shashank, your contributions have been monumental! You're tenacious and with an eye on quality, readability and a really high bar for product development. Without your persistence and creativity we wouldn't have been able to get OSM to OSS, CNCF donation, then v1 and private/public/GA launches as a managed product. And finally - selfishly - I loved learning from you! You're a wonderful human being, amazing engineer, and I really hope I get to write & review code with you again!

Hey @draychev, thanks for the kind words. Those were the indeed some of the brighter days of working on this project, and achieving the challenging goals we set out. I hope to collaborate with you again in the future!

**Comment by eduser25** [comment]
@shashankram, that was a good run. Though late, wishing you best of luck in any and all your future endeavors.
Cheers mate!

**Pull request merged**
