### PR TITLE
build: update to Go 1.17

### PR DESCRIPTION
**Pull request by Juneezee**
**Description**:

1. Enable  [module graph pruning](https://golang.org/ref/mod#graph-pruning) and [lazy module loading](https://golang.org/ref/mod#lazy-loading) by updating the `go` directive in `go.mod` to `1.17`. 

2. Update the `golang` image in Dockerfile to `1.17-alpine`.

3. Update GitHub Actions to use Go 1.17.

Go 1.16 will soon reach its end-of-life when Go 1.18 is released in February 2022. Updating the project to Go 1.17 does not introduce breaking changes to end users and should be a fairly smooth process due to [Go 1 compatibility promise](https://go.dev/doc/go1compat).

**Testing done**:

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| CI System                  | [x] |
| Upgrade                    | [x] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project?
No.

2. Is this a breaking change?
No.

### CODE REVIEW

**Review by trstringer — APPROVED** [review]

**Review by draychev — CHANGES_REQUESTED** [review]
This is great! Thank you @Juneezee!

I see that this PR contains quite large change to the `go.mod` file and it has now 2 `require` sections. I want to make sure that we review the new dependencies introduced before we merge this change. (I will take a stab at that review as soon as possible.)

**Comment by trstringer** [comment]
@draychev a quick note on multiple `require` blocks, the Go tooling separates indirect dependencies into a separate block.

**Comment by Juneezee** [comment]
> This is great! Thank you @Juneezee!
> 
> I see that this PR contains quite large change to the `go.mod` file and it has now 2 `require` sections. I want to make sure that we review the new dependencies introduced before we merge this change. (I will take a stab at that review as soon as possible.)

@draychev Hi! The additional `require` directive is used to record indirect dependencies for Go 1.17 or higher, see https://go.dev/ref/mod#go-mod-file-go.

**Review by nojnhuh — APPROVED** [review]
LGTM. The output of `go list -m all` for these changes and the main branch are exactly the same, so the same versions of the same dependencies are still being built.

**Comment by nojnhuh** [comment]
@Juneezee this PR is really close! Looks like there are a couple of small issues caught by CI.

It looks like bumping the Go version made some generated code go out of date. Following the instructions from the logs [here](https://github.com/openservicemesh/osm/runs/4719304602?check_suite_focus=true#step:5:41) should fix that issue.

Then it looks like there's a [unit test failing](https://github.com/openservicemesh/osm/runs/4719352750?check_suite_focus=true#step:7:643) because of a change in `crypto/x509`: https://go.dev/doc/go1.17.  I played with that for a bit and regenerating the test public cert to sign it with the existing private key seemed to fix that issue. Here are the exact changes I made, feel free to add these changes to this PR unless a better solution exists (/cc @draychev):
```diff
diff --git a/pkg/certificate/encode_test.go b/pkg/certificate/encode_test.go
index e30cd4c5..f7022273 100644
--- a/pkg/certificate/encode_test.go
+++ b/pkg/certificate/encode_test.go
@@ -48,7 +48,7 @@ var _ = Describe("Test tools", func() {
 		It("should have decoded the PEM into x509 certificate", func() {
 			x509Cert, err := DecodePEMCertificate([]byte(certificates.SampleCertificatePEM))
 			Expect(err).ToNot(HaveOccurred())
-			Expect(x509Cert.Subject.CommonName).To(Equal("bookbuyer.azure.mesh"))
+			Expect(x509Cert.Subject.CommonName).To(Equal("63d044c9-77c7-42ae-afdc-636a1b6ab4e2.azure.mesh"))
 		})
 	})
 })
diff --git a/pkg/certificate/providers/certmanager/certificate_manager_test.go b/pkg/certificate/providers/certmanager/certificate_manager_test.go
index 8b34eeb6..de104c3d 100644
--- a/pkg/certificate/providers/certmanager/certificate_manager_test.go
+++ b/pkg/certificate/providers/certmanager/certificate_manager_test.go
@@ -29,7 +29,7 @@ import (
 var (
 	mockCtrl         = gomock.NewController(GinkgoT())
 	mockConfigurator = configurator.NewMockConfigurator(mockCtrl)
-	cn               = certificate.CommonName("bookbuyer.azure.mesh")
+	cn               = certificate.CommonName("63d044c9-77c7-42ae-afdc-636a1b6ab4e2.azure.mesh")
 	crNotReady       = &cmapi.CertificateRequest{
 		ObjectMeta: metav1.ObjectMeta{
 			Name:      "osm-123",
diff --git a/pkg/tests/certificates/constants.go b/pkg/tests/certificates/constants.go
index fe2bb2f2..6939c9f6 100644
--- a/pkg/tests/certificates/constants.go
+++ b/pkg/tests/certificates/constants.go
@@ -4,31 +4,24 @@ package certificates
 // SampleCertificatePEM is a sample PEM cert used for tests
 // Source: https://golang.org/src/crypto/x509/example_test.go
 const SampleCertificatePEM = `-----BEGIN CERTIFICATE-----
-MIIElzCCA3+gAwIBAgIRAOsakgIV4yyGqyI9QlXD6l4wDQYJKoZIhvcNAQELBQAw
-WTE4MDYGA1UEAwwvNjNkMDQ0YzktNzdjNy00MmFlLWFmZGMtNjM2YTFiNmFiNGUy
-LmF6dXJlLm1lc2gxEDAOBgNVBAoMB0F6IE1lc2gxCzAJBgNVBAYTAlVTMB4XDTIw
-MDIxMjAyMjc0OVoXDTIwMDIxMjAyMjg0OVowMTEQMA4GA1UEChMHQUNNRSBDbzEd
-MBsGA1UEAxMUYm9va2J1eWVyLmF6dXJlLm1lc2gwggIiMA0GCSqGSIb3DQEBAQUA
-A4ICDwAwggIKAoICAQDEvG2HsGCMPXp2ZIkETP5XXuTpmaxBfVBoq3i60Dlun01i
-BE8mc3YkUZyJrxqYNCmqc9lqiDboNOs79lRXF47V9pk9l1vgKSnWWrB+AYKuWR2M
-g2ZT8QkhYc3lxqpIaL9RqmhmXISID1B2SsaJ6BBEZxXD1EaH3EZza7B5MdzU7CJc
-S7ZMV9mlECCv3Ea0+/dWjsLVw5kk75VN8UcSEX10q5weDKnktSoNfM/FJG4rrBTE
-CEkdZpiI9rkFl3UvfJ7YaxhDmudyvwxsWWITOFM7uMZkBv9DyIQq1yRh4qI++/K/
-aNZhZyYwrbAu0x8xbtkJIleA/gwKDdvBJusu2Qr+xqHghhspXpkH4KE0Tv8xDe0u
-6RJkl7eIaUe4cO0q+WTZR10CjvirEp/PFBEUiXFrms+aw6aSRUVFyX7fTHhvc9Pc
-jg+5Q72qaRIyyJ65BKO4ZRsTAzqTBlHMyr6HCIKD/Ms0OJ5PPuyKLd6uSG1gGk1e
-+LbRpZNpNtNn/EV7x3cMr8zNHA4cdsdWdYkn8zm0pnSK1r+GmmmDP6L+QfvKwxoT
-kr0rsvzAecsFfu5E+b+qNqcVoRxxazUR2td8pwovMtuw/H9BreDEbXsQ9xTAig1v
-f1+Br2yRZyHn1Zs16Brb9t4QXQDe8ybV8T/Okeh8EHSzRxOkS+LU0XqF0QXJawID
-AQABo4GBMH8wDgYDVR0PAQH/BAQDAgWgMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr
-BgEFBQcDATAMBgNVHRMBAf8EAjAAMB8GA1UdIwQYMBaAFGUkH8DwtMhY+Ik26Hwp
-utG4F2tgMB8GA1UdEQQYMBaCFGJvb2tidXllci5henVyZS5tZXNoMA0GCSqGSIb3
-DQEBCwUAA4IBAQDDUNyGRMNQz6mUlE0K+hKtv3apsW1QL885259xBP41zL3luqMa
-kFvKhaNvBDmnPUBmG14bcT/eJE9/WaQc2NgE68WB3Uup4gDxIonmKih9BD4+kjw2
-c/jJmWL4dTt3NA3kU/JoTSy+EPMnOnFk88djYmBF1u50QH1PS47r7FWDkhYw7qAn
-CJCGDhwLD968m0RWYmeRNMw4d8pFXw8mLl2EbN00k5y8dEnX2P0ciS7LgY/EmIHH
-KmPaHP5NIaW0a5riM1iXw9AzBEIfZ8hPJF+qt05v8aRBixD+ufVd/7cgm686EoeO
-tvggl4Pyw9tGpQrvZ3tL2HanuRyHiTwXZVzx
+MIIDLjCCAhYCCQCBwIhgLWe6HjANBgkqhkiG9w0BAQUFADBZMQswCQYDVQQGEwJV
+UzEQMA4GA1UECgwHQXogTWVzaDE4MDYGA1UEAwwvNjNkMDQ0YzktNzdjNy00MmFl
+LWFmZGMtNjM2YTFiNmFiNGUyLmF6dXJlLm1lc2gwHhcNMjIwMTA1MjIxMjE4WhcN
+MjIwMjA0MjIxMjE4WjBZMQswCQYDVQQGEwJVUzEQMA4GA1UECgwHQXogTWVzaDE4
+MDYGA1UEAwwvNjNkMDQ0YzktNzdjNy00MmFlLWFmZGMtNjM2YTFiNmFiNGUyLmF6
+dXJlLm1lc2gwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDD3+gqR5tL
+q3w2KZOVCJRaQ2+0bdDmqvWf4YZjsYlIWUMSxQNhX9fm6u/X/fUbwVMpDP3t2A7A
+rgJPiakti8676Ws7utVbYi2PvjLfcVtsM0UBtAqXfHN2Rg+Ne7B9AanepUeJIfzs
++/jr6MAhuhTZA/RquhLbRGJKrmHsgnGuAyGn581TXiL52HUvbJ89BbexpcQtUnqF
+Uj8JhnHWKTuoNPcLlDMRL5fRX08Zyhzxiyg66ALoZduHNu6HV/Z0YXHlxePKZCIR
+rbx58a74q6zYBTWdWqkKhKF1wFYWBwi2ppIPW2U47TOV0IsnWs9o7DsWkFMpf97S
+pE7vSyxpPefNAgMBAAEwDQYJKoZIhvcNAQEFBQADggEBABzMgrcHWw05eNvK+XH4
+6DRzR3X37N13fKt2kYCPsuosnuti5MRVDVcSvOs4/Z47u9Ade4DOeNeCVTF9TZ4q
+qeOdaR7qY/Pw5TUPlQqTpgr6GBQ/JF0hXQ3aAF1kfwVmLZvt4IirISUGluKU1Cwi
+BYjefckldL3R1ifckpOC49OBZru2v6YlySQ6+0b7QXnzCMwrbbk/mlaC/Hls7ZN8
+Buxx3GKtD73M3CCxeO8zpw9FeX6NSGh5UwsHcORTN7Cv7MMlTlJmUKKTovzzguGj
+e+SS+bQ5uuXLb3bomn54Tq8nVFlZJheNRFfSSaqXTIb6SFngVdmMtp1QD/BJ7ke3
+v+I=
 -----END CERTIFICATE-----`
 
 // SamplePrivateKeyPEM is a sample PEM private key used for tests
```

After those two small changes we should be able to merge this.

**Comment by Juneezee** [comment]
@nojnhuh Good catch! I have committed the two changes and rebased onto the latest `main` branch. Please take a look again. Thanks!

**Pull request merged**
