### PR TITLE
Self-nomination for Maintainer role

### PR DESCRIPTION
**Pull request by mudit-01**
Hi Maintainers
I've been contributing to OSM for a year now. CLI, documentation, and other areas are where I have contributed. I accept each and every prerequisite for becoming a Maintainer. Hence self-nominating myself for the role of a Maintainer. Thanks!

Signed-off-by: mudit singh <mudit.singh@india.nec.com>

**Description**:

**Testing done**: NA

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [ ] |
| CI System                  | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [ ] |
| Demo                       | [ ] |
| Documentation              | [ ] |
| Egress                     | [ ] |
| Ingress                    | [ ] |
| Install                    | [ ] |
| Networking                 | [ ] |
| Observability              | [ ] |
| Performance                | [ ] |
| SMI Policy                 | [ ] |
| Security                   | [ ] |
| Sidecar Injection          | [ ] |
| Tests                      | [ ] |
| Upgrade                    | [ ] |
| Other                      | [x ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project?
    -   Did you notify the maintainers and provide attribution?

2. Is this a breaking change?

3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)?

### CODE REVIEW

**Review by keithmattix — APPROVED** [review]
Thank you for all of your contributions to the project!

**Review by trstringer — APPROVED** [review]
+1. Thank you for everything!

**Comment by mudit-01** [comment]
Thanks! @keithmattix and @trstringer. :slightly_smiling_face:
Can we merge this PR?

**Comment by trstringer** [comment]
We need to wait for a majority vote prior to merging!

// @nojnhuh @jaellio @shalier @steeling

**Comment by mudit-01** [comment]
@nojnhuh @jaellio @shalier @steeling waiting for your vote PTAL

**Comment by jaellio** [comment]
@mudit-01 Could you please provide 10 PR's that you believe demonstrate expertise across the OSM codebase? Thanks!

**Comment by mudit-01** [comment]
Hi @jaellio below are requested PRs that I have been contributing in OSM in the area of CLI and doc

**Comment by mudit-01** [comment]
@jaellio waiting for your views on this PR. Thanks!

**Comment by mudit-01** [comment]
@jaellio waiting for your review, Thanks!

**Pull request closed without merging**
