### PR TITLE
e2e: Add pod restart checks and Fail tests if seen by default

### PR DESCRIPTION
**Pull request by eduser25**
None of the tests we currently have should be seeing pod restarts.
This is put in place to rule out unwanted restart issues, but other
tests implementing restarts should be put in place.

Signed-off-by: Eduard Serra <eduser25@gmail.com>

**Affected area**:

- Control Plane          [x ]
- Tests                  [ x]

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?
No

### CODE REVIEW

**Review by SanyaKochhar — APPROVED** [review]

**Review by snehachhabria — APPROVED** [review]

**Review by shashankram — COMMENTED** [review]
This will break for the test where the controller is intentionally restarted. Please fix this.

**Comment by shashankram** [comment]
> This will break for the test where the controller is intentionally restarted. Please fix this.

Luckily, we don't restart the controller but rather delete it, and spin up a new one. Hope that doesn't mess with the verification checks!

**Comment by eduser25** [comment]
good. I did check the restart increase part by issuing sigabort on the container application on the node itself. Did not remember we had a restart test...

**Comment by shashankram** [comment]
> good. I did check the restart increase part by issuing sigabort on the container application on the node itself. Did not remember we had a restart test...

I didn't either, and its not even a restart test, but rather a new controller pod! If we had a way to force exit controller via an endpoint like `/forcequit`, we could test actual restart as well.

**Pull request merged**
