### PR TITLE
config/MeshConfig: Update control plane to v1alpha3

### PR DESCRIPTION
**Pull request by keithmattix**
Updates the OSM control plane to use the new v1alpha3 version, and
add a couple of convenience methods. Also, add install capabilities
by updating the Helm chart

Part of #4653 

Signed-off-by: Keith Mattix II <keithmattix2@gmail.com>

**Description**:

**Testing done**:
Update units to reference new control plane version. Actual functionality will be tested in the next PR

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [X] |
| CI System                  | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [X] |
| Demo                       | [ ] |
| Documentation              | [ ] |
| Egress                     | [ ] |
| Ingress                    | [ ] |
| Install                    | [ ] |
| Networking                 | [ ] |
| Observability              | [ ] |
| Performance                | [ ] |
| SMI Policy                 | [ ] |
| Security                   | [ ] |
| Sidecar Injection          | [ ] |
| Tests                      | [ ] |
| Upgrade                    | [ ] |
| Other                      | [ ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project? no
    -   Did you notify the maintainers and provide attribution? no

2. Is this a breaking change? no

3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? Not yet applicable

### CODE REVIEW

**Comment by steeling** [comment]
Is there a bug linked to this? Can you explain why we need a whole new version API? If we're just adding a field I would expect us to be able to add that to the existing API with no backwards incompatible changes.

We would just need to have our init container switch from a Create to an Apply when generating the CRD's

**Comment by keithmattix** [comment]
@steeling adding the related issue; this is a multi-part PR. The reason I opted for a new version is because this is coming after a release (v1.1) and we're likely going to be releasing this feature as a patch. I think the explicitness is helpful even though the change would be backward-compatible

**Comment by steeling** [comment]
> @steeling adding the related issue; this is a multi-part PR. The reason I opted for a new version is because this is coming after a release (v1.1) and we're likely going to be releasing this feature as a patch. I think the explicitness is helpful even though the change would be backward-compatible

There's a lot of overhead in maintaining multiple versions. And reasoning about version change compatibility can be tricky. I'd push for a policy of only bumping versions on non-backwards compatible changes, as is [standard for CRD's](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md#adding-a-field).

Reducing the number of API's we need to maintain is going to pay dividends down the road

**Comment by keithmattix** [comment]
Fair point; I wasn't aware of that guidance in sig-architecture. I'd love a centralized guide for these conventions, but that's a separate matter.

So since #4671 has already been merged; what do you suggested we do? cc @shashankram

**Comment by shashankram** [comment]
> > @steeling adding the related issue; this is a multi-part PR. The reason I opted for a new version is because this is coming after a release (v1.1) and we're likely going to be releasing this feature as a patch. I think the explicitness is helpful even though the change would be backward-compatible
> 
> There's a lot of overhead in maintaining multiple versions. And reasoning about version change compatibility can be tricky. I'd push for a policy of only bumping versions on non-backwards compatible changes, as is [standard for CRD's](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md#adding-a-field).
> 
> Reducing the number of API's we need to maintain is going to pay dividends down the road

In general, I agree with reducing the burden by not bumping API versions for backward compatible fields. When we bumped the version from v1alpha1->v1alpha2 previously, it was done because there were several new fields, and also because we wanted to exercise the conversion webhook path, so it made sense back then.

I am not opposed to bumping the version here, but this should be accompanied by completely removing `v1alpha1` types from the code and docs, we we don't have an ever increasing list of versions to maintain.

**Comment by shashankram** [comment]
> Fair point; I wasn't aware of that guidance in sig-architecture. I'd love a centralized guide for these conventions, but that's a separate matter.
> 
> So since #4671 has already been merged; what do you suggested we do? cc @shashankram

@keithmattix since this seems to be well documented in the API convention, let's revert #4671 and add the field to the v1alpha2 version. @steeling, thanks for sharing the API guide regarding this.

**Comment by keithmattix** [comment]
Closing due to discussion.

**Pull request closed without merging**
