### PR TITLE
Adjusting links for use on repo and website

### PR DESCRIPTION
**Pull request by bridgetkromhout**
Based on feedback from @shashankram in https://github.com/openservicemesh/osm/pull/2636#discussion_r584001615 I'm trying a relative link style to see if it shows up correctly on both the website and the github repo.

Signed-off-by: Bridget Kromhout <bridget@kromhout.org>

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
The links now work correctly on https://github.com/bridgetkromhout/osm/blob/relative-links/docs/content/docs/patterns/observability/_index.md and on https://deploy-preview-2647--osm-docs.netlify.app/docs/patterns/observability/.

**Review by shashankram — COMMENTED** [review]
Do we have to start using such relative paths throughout the docs going forward? Its easier to mess up relative paths than absolute ones, so not sure if this is the best approach, or if there is even an alternative.

**Comment by bridgetkromhout** [comment]
As I understand it, we have two choices for [links](https://github.com/openservicemesh/osm/blob/main/docs/README.md#links) on this sort of generated site:
* absolute links to github itself
* relative links without the initial `/`

As illustrated in the error that I'm fixing in this PR, we do not have a singular authoritative full path that covers both cases.

**Comment by shashankram** [comment]
> As I understand it, we have two choices for [links](https://github.com/openservicemesh/osm/blob/main/docs/README.md#links) on this sort of generated site:
> 
> * absolute links to github itself
> * relative links without the initial `/`
> 
> As illustrated in the error that I'm fixing in this PR, we do not have a singular authoritative full path that covers both cases.

Do we need to update other references of the form `/docs/xyz` and `/docs/content/docs/xyz`?

**Review by shashankram — APPROVED** [review]

**Review by snehachhabria — APPROVED** [review]

**Comment by shashankram** [comment]
@bridgetkromhout kindly squash before merge...

**Comment by bridgetkromhout** [comment]
> Do we need to update other references of the form /docs/xyz and /docs/content/docs/xyz?

@shashankram Yes; I've adjusted several more pages that worked on github but did not work on the generated website.

**Comment by bridgetkromhout** [comment]
I'll squash when it's ready, but based on the error in https://deploy-preview-2647--osm-docs.netlify.app/docs/scale/images/scale/256-1.5-cpu.png I still don't have it quite right. Fixing shortly.

**Review by michelleN — APPROVED** [review]

**Comment by bridgetkromhout** [comment]
@flynnduism is looking into our options for paths that will work for both github and the website.

**Comment by bridgetkromhout** [comment]
I have fixed all the issues I found on the website and github for various links and images. Summary of fixes:

1) HA page

- https://docs.openservicemesh.io/docs/ha/ had several broken images due to absolute paths
- https://deploy-preview-2647--osm-docs.netlify.app/docs/ha/ now has the embedded images working.
- https://github.com/openservicemesh/osm/blob/main/docs/content/docs/HA.md previously worked but is moved to a directory to allow for the above fix: https://github.com/bridgetkromhout/osm/blob/relative-links/docs/content/docs/HA/_index.md

2) OSM Components & Interactions page

- https://github.com/openservicemesh/osm/blob/main/docs/content/docs/design_concepts/osm_components_interactions.md had a broken link.
- The link now works on github with the necessary path changes: https://github.com/bridgetkromhout/osm/blob/relative-links/docs/content/docs/design_concepts/osm_components_interactions/_index.md
- The link also still works on the website
https://deploy-preview-2647--osm-docs.netlify.app/docs/design_concepts/osm_components_interactions/

3) Manual demo 
 
- links were incorrect for github, and are now working on github and the website. Needed to move the file to a directory: https://github.com/bridgetkromhout/osm/blob/relative-links/docs/content/docs/install/manual_demo/_index.md


4) Observability page

- The links for the metrics page and the logs page were incorrect for github (but correct for the website at https://docs.openservicemesh.io/docs/patterns/observability/)
- Fixed as seen in https://github.com/bridgetkromhout/osm/blob/relative-links/docs/content/docs/patterns/observability/_index.md
- And still working correctly on https://deploy-preview-2647--osm-docs.netlify.app/docs/patterns/observability/

5) Scale page 

- Images linked on the scale page now work on both github and the website
- https://deploy-preview-2647--osm-docs.netlify.app/docs/scale/ fixes the image rewrites that were previously going to https://docs.openservicemesh.io/docs/content/docs/images/scale/512-1.5-cpu.png 
- Needed to move https://github.com/openservicemesh/osm/blob/main/docs/content/docs/scale.md to a directory as in https://github.com/bridgetkromhout/osm/blob/relative-links/docs/content/docs/scale/_index.md

**Pull request merged**
