### PR TITLE
[helm chart] ServiceMonitor support

### PR DESCRIPTION
**Pull request by nlamirault**
**Description**:
Enable OSM monitoring using a ServiceMonitor

See : #4699 

**Testing done**:

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [ ] |
| CI System                  | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [ ] |
| Demo                       | [ ] |
| Documentation              | [ ] |
| Egress                     | [ ] |
| Ingress                    | [ ] |
| Install                    | [ ] |
| Networking                 | [ ] |
| Observability              | [ ] |
| Performance                | [ ] |
| SMI Policy                 | [ ] |
| Security                   | [ ] |
| Sidecar Injection          | [ ] |
| Tests                      | [ ] |
| Upgrade                    | [ ] |
| Other                      | [x ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project?
    -   Did you notify the maintainers and provide attribution?

2. Is this a breaking change?
No.

4. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)?

### CODE REVIEW

**Comment by shashankram** [comment]
@nlamirault thanks for contributing. Could you open up an issue describing the need for this change so we can discuss further. Thanks

**Comment by nlamirault** [comment]
Done @shashankram

**Review by keithmattix — APPROVED** [review]
Since the serviceMonitor creation is hidden behind a condition (that's defaulted to false), I don't object to such a community-oriented change. I'll note that this change will only add a servicemonitor for osm-controller and not osm-injector or osm-bootstrap.

**Comment by jaellio** [comment]
@nlamirault Could you please update the charts by running `make check-charts` at the root of the project?

**Comment by nlamirault** [comment]
`make check-charts` where do you find this command ? @jaellio

**Comment by jaellio** [comment]
Hi @nlamirault, at the root of the OSM project there is a `[makefile](https://github.com/openservicemesh/osm/blob/4d6d8c9d7c77df92a8e0a13de29f05b192f7bb92/Makefile#L96)` that defines the `check-charts` tag. The `check-charts` task will regenerate `charts/osm/README.md`. In your branch, if you navigate to the root of the repository and run `make check-charts` the task will run and you can push a new commit. Let me know if you have any questions!

**Comment by jaellio** [comment]
Closing this PR for now due to inactivity. @nlamirault please comment on the PR and tag me if you would like this to be reopened! Thanks!

**Pull request closed without merging**
