### PR TITLE
pkg/envoy: Changed ServiceAccount field from type string to type service.K8sServiceAccount

### LINKED ISSUE #2681: pkg/envoy: PodMetadata's ServiceAccount field of type string should be of type service.K8sServiceAccount instead
The struct `PodMetadata` has a field `ServiceAccount` which is of type `string`: https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/envoy/proxy.go#L48

A better type for this is `K8sServiceAccount`: https://github.com/openservicemesh/osm/blob/release-v0.8/pkg/service/types.go#L22-L25

### PR DESCRIPTION
**Pull request by sheetalsingala**
Fixes #2681 

**Description**:

**Affected area**:

- New Functionality      [ ]
- Documentation          [ ]
- Install                [ ]
- Control Plane          [ ]
- CLI Tool               [ ]
- Certificate Management [ ]
- Networking             [ ]
- Metrics                [ ]
- SMI Policy             [ ]
- Security               [ ]
- Tests                  [ ]
- CI System              [ ]
- Performance            [ ]
- Other                  [ ]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?

### CODE REVIEW

**Comment by shashankram** [comment]
@sheetalsingala thanks for the PR, you also need to update the unit tests to reflect this change. You can run the unit tests using `go test ./pkg/...` and identify tests using the older type and change them accordingly.

**Review by michelleN — APPROVED** [review]
thank you @sheetalsingala !

**Review by draychev — APPROVED** [review]
Thank you @sheetalsingala !!
This is a great change!

**Comment by shashankram** [comment]
@mergify rebase

**Pull request merged**
