### PR TITLE
feat(pkg/*): change IsPermissiveTrafficPolicyMode to check identity

### PR DESCRIPTION
**Pull request by steeling**
change IsPermissiveTrafficPolicyMode to check if the identity is the gateway. This is so that the gateway can no about all services in the cluster.

Add the serviceIdentity to every call of IsPermissiveTrafficPolicyMode.
Move some of the utils Serving functionality to pkg/envoy/ads to avoid import cycles.

Signed-off-by: Sean Teeling <seanteeling@microsoft.com>

Please mark with X for applicable areas.

-->
**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [ x] |
| Documentation              | [ ] |
| Install                    | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [x ] |
| Ingress                    | [ ] |
| Egress                     | [ ] |
| Networking                 | [x ] |
| Observability              | [ ] |
| SMI Policy                 | [ ] |
| Sidecar Injection          | [ ] |
| Security                   | [ ] |
| Upgrade                    | [ ] |
| Tests                      | [ ] |
| CI System                  | [ ] |
| Demo                       | [ ] |
| Performance                | [ ] |
| Other                      | [ ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project?
    -   Did you notify the maintainers and provide attribution?

No

1. Is this a breaking change?
No

### CODE REVIEW

**Review by shashankram — CHANGES_REQUESTED** [review]
@steeling Permissive traffic policy mode is not meant to be used this way, as a hack to allow service discovery for a gateway.

Instead, I propose creating a new API in meshCatalog that allows a gateway to perform mesh wide service discovery similar to permissive mode. Refer to `ListOutboundTrafficPolicies()` for an example of how this is done.

Permissive mode is meant to be a mesh wide global configuration for intra-mesh connectivity. Conflating this with service discovery for gateway does not seem correct to me.

**Comment by steeling** [comment]
> ListOutboundTrafficPolicies

Gotcha.. for now this should be as simple as modifying each call to IsPermissiveMode to be `mc.configurator.IsPermissiveMode() || mc.IsGateway(id)`
See https://docs.google.com/document/d/1sA03IwqC6tuJpCleGMakQpHzwFJ5ulfxzCq7iSXSqZc/edit#

**Comment by shashankram** [comment]
> > ListOutboundTrafficPolicies
> 
> Gotcha.. for now this should be as simple as modifying each call to IsPermissiveMode to be `mc.configurator.IsPermissiveMode() || mc.IsGateway(id)`
> See https://docs.google.com/document/d/1sA03IwqC6tuJpCleGMakQpHzwFJ5ulfxzCq7iSXSqZc/edit#

With the work that I am doing for #3501, we will be able to identify a Gateway using `proxy.Kind()`. Based on this, we could call a function in the `MeshCataloger` interface for whatever configs are required by the multicluster gateway.

Would that work for you?

**Comment by steeling** [comment]
Closing in favor of https://github.com/openservicemesh/osm/pull/3552

**Pull request closed without merging**
