### PR TITLE
Began structure of site navigation

### PR DESCRIPTION
**Pull request by phillipgibson**
**Description**: Beginning structure and layout for site navigation for openservicemesh.io docs site.

**Affected area**:

- New Functionality      [ ]
- Documentation          [X]
- Install                [ ]
- Control Plane          [ ]
- CLI Tool               [ ]
- Certificate Management [ ]
- Networking             [ ]
- Metrics                [ ]
- SMI Policy             [ ]
- Security               [ ]
- Tests                  [ ]
- CI System              [ ]
- Performance            [ ]
- Other                  [ ]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution? No

### CODE REVIEW

**Comment by bridgetkromhout** [comment]
This looks good. Do you want to update the link in https://github.com/openservicemesh/osm#osm-design since we're moving away from that singular DESIGN.md file? I think that will prevent us from having a broken link there: https://github.com/openservicemesh/osm/blob/main/README.md#osm-design

**Review by bridgetkromhout — APPROVED** [review]

**Comment by flynnduism** [comment]
❤️ 

Preview link for the changes in this PR
https://deploy-preview-2471--osm-docs.netlify.app/

**Review by michelleN — COMMENTED** [review]
Looks like this PR needs a rebase!

**Comment by phillipgibson** [comment]
let me rebase

**Comment by phillipgibson** [comment]
It should be current now @michelleN

**Comment by phillipgibson** [comment]
Will re-submit.

**Pull request closed without merging**
