### PR TITLE
envoy: Update to Envoy version to 1.20.0

### LINKED ISSUE #4141: Windows nightly job is broken
Windows nightly job is failing due to an Envoy issue.

See https://github.com/envoyproxy/envoy/pull/18163

### PR DESCRIPTION
**Pull request by davinci26**
Updates Envoy version to 1.20 and validated
that there are no warnings with the existing config.

Should also fix #4141

Signed-off-by: Sotiris Nanopoulos <sonanopo@microsoft.com>

**Description**:

**Testing done**:

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [ ] |
| CI System                  | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [ ] |
| Demo                       | [ ] |
| Documentation              | [ ] |
| Egress                     | [ ] |
| Ingress                    | [ ] |
| Install                    | [ ] |
| Networking                 | [ ] |
| Observability              | [ ] |
| Performance                | [ ] |
| SMI Policy                 | [ ] |
| Security                   | [ ] |
| Sidecar Injection          | [ ] |
| Tests                      | [ ] |
| Upgrade                    | [ ] |
| Other                      | [ ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project?
    -   Did you notify the maintainers and provide attribution?

2. Is this a breaking change?

### CODE REVIEW

**Comment by davinci26** [comment]
@anrossi

**Comment by anrossi** [comment]
Don't close this issue yet. The work is ongoing.

**Comment by anrossi** [comment]
@rectified95 FYI

**Comment by draychev** [comment]
Thank you @anrossi and @rectified95 for working on this!

**Pull request closed without merging**
