### PR TITLE
add multicluster design doc link

### PR DESCRIPTION
**Pull request by steeling**
Add the [multicluster design doc](https://docs.google.com/document/d/1Do9iw55mRuQii6W_l8ULbDiVZb1iG7dLhL75Nz_D8OE) for review

### CODE REVIEW

**Comment by keithmattix** [comment]
Hey, can you modify https://github.com/openservicemesh/osm/blob/main/.github/workflows/auto-assign.yml#L3 to react on `pull_request_target` instead of `pull_request`? Looks like a weird permission issue is preventing the auto-assign

**Comment by steeling** [comment]
> Hey, can you modify https://github.com/openservicemesh/osm/blob/main/.github/workflows/auto-assign.yml#L3 to react on `pull_request_target` instead of `pull_request`? Looks like a weird permission issue is preventing the auto-assign

done, let's see if that fixes it

**Comment by keithmattix** [comment]
Looks like it didn't. To keep this going, I'm going to assign myself, @jsturtevant @schristoff, and @jaellio to this design doc to review it

**Review by keithmattix — APPROVED** [review]
Read through the doc and it looks good to me. Approved

**Review by jsturtevant — APPROVED** [review]

**Pull request closed without merging**
