### PR TITLE
[RFC] Replacing empty slice literals with nil slice declarations

### PR DESCRIPTION
**Pull request by draychev**
This PR replaces empty slice declaration using a nil slice declaration.

This does functionally change the code. These are not equivalent, however the second one seems to be subtly more efficient.

Found these using:
```bash
grep -Iir ":= \[\]" $(find . -name '*.go') | grep '\{\}'
```

---

# Proposal
Make it a guideline (so where possible) for OSM contributions to use a nil slice declaration.
So prefer `var x []string`, and not `x := []string{}`

### CODE REVIEW

**Comment by allenlsy** [comment]
Curious, what is the functional difference between `var x []string` and `x := []string{}`

**Review by shashankram — APPROVED** [review]
Thanks
+1 to using nil slice instead of empty slice where necessary.

**Comment by shashankram** [comment]
> Curious, what is the functional difference between `var x []string` and `x := []string{}`

https://stackoverflow.com/questions/44305170/nil-slices-vs-non-nil-slices-vs-empty-slices-in-go-language

**Review by snehachhabria — APPROVED** [review]

**Comment by draychev** [comment]
> Curious, what is the functional difference between `var x []string` and `x := []string{}`

@allenlsy It a subtle and the two are not equivalent. The second one is an allocation. I've heard of this referred to as no glass and empty glass.
In our repository we have a mix of both. 

Here is an example of where these differ:
https://play.golang.org/p/Yd6jei06m9y
image

**Pull request merged**
