### PR TITLE
log: Bimodal logging of Pod metadata

### PR DESCRIPTION
**Pull request by draychev**
**Description**:

**Affected area**:

- New Functionality      [ ]
- Documentation          [ ]
- Install                [ ]
- Control Plane          [ ]
- CLI Tool               [ ]
- Certificate Management [ ]
- Networking             [ ]
- Metrics                [ ]
- SMI Policy             [ ]
- Security               [ ]
- Tests                  [ ]
- CI System              [ ]
- Demo                   [ ]
- Performance            [ ]
- Other                  [ ]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?

### CODE REVIEW

**Comment by shashankram** [comment]
This looks promising!

**Comment by draychev** [comment]
@ksubrmnn take a look at this PR for ideas on how to solve #2924

**Comment by shashankram** [comment]
> @ksubrmnn take a look at this PR for ideas on how to solve #2924

@draychev I made some enhancements to the existing logging to reduce repeated logging of the same proxy info in every log line (pod metadata, serial number, UUID etc.). I suggest tweaking logging further based on the snippet below:
https://github.com/openservicemesh/osm/blob/main/pkg/envoy/proxy.go#L52-L58

We could change `proxy.String() -> proxy.Log()`, and have this utility return proxy related info to be logged as a string.

**Comment by draychev** [comment]
Closing this as @nojnhuh is working on another solution for this!

**Comment by draychev** [comment]
Addressed with: https://github.com/openservicemesh/osm/blob/4757443cded5e346a8e11f59ee71f8a91c7c87ea/pkg/envoy/proxy.go#L55-L61

**Pull request closed without merging**
