### PR TITLE
change port 808X to 707X in example readme

### PR DESCRIPTION
**Pull request by wonderflow**
Please describe the motivation for this PR and provide enough
information so that others can review it.

fix the readme that ports are 707X not 808X

Please mark with X for applicable areas.

- New Functionality      [ ]
- Documentation          [x]
- Install                [ ]
- Control Plane          [ ]
- CLI Tool               [ ]
- Certificate Management [ ]
- Networking             [ ]
- Metrics                [ ]
- SMI Policy             [ ]
- Security               [ ]
- Tests / CI System      [ ]
- Other                  [ ]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?

No

### CODE REVIEW

**Comment by wonderflow** [comment]
@shashankram  I followed [the instruction](https://github.com/openservicemesh/osm/pull/1646/files#diff-c85fd69b696973d871f93bf7abbb4597L91) and 808X didn't work.

**Comment by shashankram** [comment]
> @shashankram I followed [the instruction](https://github.com/openservicemesh/osm/pull/1646/files#diff-c85fd69b696973d871f93bf7abbb4597L91) and 808X didn't work.

Are you running into https://github.com/openservicemesh/osm/issues/1483?

Check out https://github.com/openservicemesh/osm/commit/de4c1831c70609832132b28ae4b2fe4aa431786e which provides a workaround.

You can override the ports as described in https://github.com/openservicemesh/osm/tree/main/docs/example#view-the-application-uis

**Comment by wonderflow** [comment]
@shashankram   The default port will be coverd by the script `BOOKBUYER_LOCAL_PORT=7070 BOOKSTOREv1_LOCAL_PORT=7071 BOOKSTOREv2_LOCAL_PORT=7072 BOOKTHIEF_LOCAL_PORT=7073 ./scripts/port-forward-all.sh` in readme, so only 707X works

**Comment by shashankram** [comment]
> @shashankram The default port will be coverd by the script in readme, so only 707X works
> 
> `BOOKBUYER_LOCAL_PORT=7070 BOOKSTOREv1_LOCAL_PORT=7071 BOOKSTOREv2_LOCAL_PORT=7072 BOOKTHIEF_LOCAL_PORT=7073 ./scripts/port-forward-all.sh`

The default ports are 8080, 8081, 8082, 8083. I don't understand what you mean, but if the default ports do not work in your environment then you can override it as shown above.

**Comment by wonderflow** [comment]
@shashankram  ok, never mind, I will close

**Pull request closed without merging**
