### PR TITLE
fix(): reduce minimum tls version for control plane

### PR DESCRIPTION
**Pull request by whitneygriffith**
**Description**: Envoy proxy fails if tlsMaxProtocolVersion is set to TLSv1_2 because the minimum tls version for control plane was set to TLSv1_3

**Testing done**:

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [ ] |
| CI System                  | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [x] |
| Demo                       | [ ] |
| Documentation              | [ ] |
| Egress                     | [ ] |
| Ingress                    | [ ] |
| Install                    | [ ] |
| Networking                 | [ ] |
| Observability              | [ ] |
| Performance                | [ ] |
| SMI Policy                 | [ ] |
| Security                   | [ ] |
| Sidecar Injection          | [ ] |
| Tests                      | [ ] |
| Upgrade                    | [ ] |
| Other                      | [ ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project?
    -   Did you notify the maintainers and provide attribution?

2. Is this a breaking change?

3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)?

### CODE REVIEW

**Comment by whitneygriffith** [comment]
Resolves #5282

**Review by keithmattix — COMMENTED** [review]
The main branch has drifted pretty far from our release branches. You may want to make your PR based on release 1.2 branch instead of main

**Comment by jaellio** [comment]
> The main branch has drifted pretty far from our release branches. You may want to make your PR based on release 1.2 branch instead of main

@keithmattix To maintain our previous workflow should the changes including e2e tests first be made on main and then backported to v1.2?

**Comment by jaellio** [comment]
Closing in favor of #5292

**Review by keithmattix — APPROVED** [review]

**Review by jaellio — APPROVED** [review]

**Pull request merged**
