### PR TITLE
owners: add @trstringer as a codeowner maintainer

### PR DESCRIPTION
**Pull request by shashankram**
**Description**:
Adds @trstringer as a codeowner maintainer.

@trstringer has been contributing to the
day-to-day maintenance of this project,
documentation improvements, package upgrades
to address vulnerabilities, bug-reporting
enhancements, code reviews etc.

**Maintainers**, if you agree with this nomination,
leave a "+1" comment and approve the PR (do not
merge it).

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| Other                      | [X] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project? `no`
    -   Did you notify the maintainers and provide attribution?

### CODE REVIEW

**Review by nojnhuh — APPROVED** [review]
+1

**Review by jaellio — APPROVED** [review]
+1

**Comment by trstringer** [comment]
Thank you for the nomination, @shashankram! I am honored, and I agree to all requirements of becoming a Maintainer.

**Comment by shashankram** [comment]
This is good to merge as a majority (3/5) of the existing maintainers are in agreement.

**Pull request merged**
