### PR TITLE
trafficpolicy: extend HTTPRouteMatch to prefix and exact path matching

### PR DESCRIPTION
**Pull request by shashankram**
**Description**:
Currently, OSM only supports regex based path matching for
HTTP routes. Additional path matching semantics are required
for ingress, specifically `exact` and `prefix` based matching.

This change updates the `HTTPRouteMatch` type to make HTTP
path matching generic enough to match based on regex, exact,
and prefix matching. Functionally, since all existing code is
based on regex based path matching, all HTTP routes specify
the path match type as `regex`.

Required for #2798

Signed-off-by: Shashank Ram <shashr2204@gmail.com>

**Affected area**:

- New Functionality      [ ]
- Documentation          [ ]
- Install                [ ]
- Control Plane          [X]
- CLI Tool               [ ]
- Certificate Management [ ]
- Networking             [ ]
- Metrics                [ ]
- SMI Policy             [ ]
- Security               [ ]
- Tests                  [ ]
- CI System              [ ]
- Demo                   [ ]
- Performance            [ ]
- Other                  [ ]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?
`No`

### CODE REVIEW

**Review by michelleN — APPROVED** [review]
Thanks @shashankram. If I'm understanding this correctly the prefix and exact matches will be implemented and tested with a follow up PR for ingress support which is 👍. If that weren't the case, I'd recommend we add some comments to the code mentioning those types are unimplemented.

**Comment by shashankram** [comment]
> Thanks @shashankram. If I'm understanding this correctly the prefix and exact matches will be implemented and tested with a follow up PR for ingress support which is 👍. If that weren't the case, I'd recommend we add some comments to the code mentioning those types are unimplemented.

Thanks for the review @michelleN. Yes, I will be implementing the prefix and exact matching on HTTP paths in a follow-up, but dropped the additional types in there to build up the context.

**Review by eduser25 — APPROVED** [review]
lgtm

**Comment by shashankram** [comment]
> > Thanks @shashankram. If I'm understanding this correctly the prefix and exact matches will be implemented and tested with a follow up PR for ingress support which is 👍. If that weren't the case, I'd recommend we add some comments to the code mentioning those types are unimplemented.
> 
> Thanks for the review @michelleN. Yes, I will be implementing the prefix and exact matching on HTTP paths in a follow-up, but dropped the additional types in there to build up the context.

https://github.com/openservicemesh/osm/pull/3066 leverages the newly added patch match types.

**Pull request merged**
