### PR TITLE
Enable WebSocket upgrade on Envoy for HTTP connections

### LINKED ISSUE #4725: WebSocket support
**Please describe the Improvement and/or Feature Request**
Currently establishing WebSocket connections to in-cluster services can fail in envoy producing upgrade failure logs.

Envoy however does support WebSocket upgrades given the appropriate upgrade config. This upgrade config should be supported in OSM.

**Scope (please mark with X where applicable)**
- New Functionality          [x ]
- Install                    [ ]
- SMI Traffic Access Policy  [ ]
- SMI Traffic Specs Policy   [ ]
- SMI Traffic Split Policy   [ ]
- Permissive Traffic Policy  [ ]
- Ingress                    [ ]
- Egress                     [ ]
- Envoy Control Plane        [x]
- CLI Tool                   [ ]
- Metrics                    [ ]
- Certificate Management     [ ]
- Sidecar Injection          [ ]
- Logging                    [ ]
- Debugging                  [ ]
- Tests                      [ ]
- CI System                  [ ]
- Demo                       [ ]
- Project Release            [ ]

**Possible use cases**
Hosting Services that accept WebSocket connections

### PR DESCRIPTION
**Pull request by dasMulli**
**Description**:
Allows to set allowed http upgrade type so that envoy will pass the requested upgrade request upstream.
Implements #4725 by allowing to set the `websocket` upgrade type.

Closes #4725 

**Testing done**:  tested end-to-end on a test cluster

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [ ] |
| CI System                  | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [ ] |
| Demo                       | [ ] |
| Documentation              | [ ] |
| Egress                     | [x] |
| Ingress                    | [x] |
| Install                    | [ ] |
| Networking                 | [x] |
| Observability              | [ ] |
| Performance                | [ ] |
| SMI Policy                 | [ ] |
| Security                   | [ ] |
| Sidecar Injection          | [ ] |
| Tests                      | [ ] |
| Upgrade                    | [ ] |
| Other                      | [ ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project? no
    -   Did you notify the maintainers and provide attribution?

3. Is this a breaking change? no

4. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)? no

### CODE REVIEW

**Review by shashankram — COMMENTED** [review]
@dasMulli Based on https://github.com/openservicemesh/osm/issues/4725#issuecomment-1124236265, we don't need to expose this upgrade type in the configs. We can directly set this field in the http_connection_manager for now as we don't intend to support `connect` yet.

**Comment by dasMulli** [comment]
@shashankram sorry I misunderstood that. updated.

**Comment by dasMulli** [comment]
Not sure how I closed the PR (working remotely from a codespaces instance) but apparently I don’t have the permission to reopen it

**Comment by shashankram** [comment]
> Not sure how I closed the PR (working remotely from a codespaces instance) but apparently I don’t have the permission to reopen it

I think force pushing to your branch caused this. I have had this happen as well. Since I can't seem to reopen it either, could you open a new PR? Thanks

**Comment by dasMulli** [comment]
@shashankram followed up with #4741

**Pull request closed without merging**
