### PR TITLE
Golang errors pkg

### PR DESCRIPTION
**Pull request by allenlsy**
**Description**:

This PR partially resolves https://github.com/openservicemesh/osm/issues/4524

* Removes "github.com/pkg/errors" package from the repo
* Wrap errors wherever possible rather than using the string format of the error as part of the message

**Testing done**:

No functionality changes in this PR. Unit test passes.

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [ ] |
| CI System                  | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [ ] |
| Demo                       | [ ] |
| Documentation              | [ ] |
| Egress                     | [ ] |
| Ingress                    | [ ] |
| Install                    | [ ] |
| Networking                 | [ ] |
| Observability              | [ ] |
| Performance                | [ ] |
| SMI Policy                 | [ ] |
| Security                   | [ ] |
| Sidecar Injection          | [ ] |
| Tests                      | [ ] |
| Upgrade                    | [ ] |
| Other                      | [ ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project?
    -   Did you notify the maintainers and provide attribution?

No

2. Is this a breaking change?

No

3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)?

Not required

### CODE REVIEW

**Comment by trstringer** [comment]
@keithmattix, where do you see those linting errors? Doesn't look like they are getting surfaced with the CI run. But if we will introduce linting errors than my vote would be to go with fixing them in this same PR so we don't have to ignore failures.

**Comment by keithmattix** [comment]
@trstringer apologies, I meant warnings. They come from go-staticcheck (at least in VSCode)
image

**Comment by allenlsy** [comment]
@keithmattix From what I see, those lint errors are from the "Unchanged files with check annotations" section, not because of capitalization. I remember previously we can ignore that. I think this is a new feature in PR. I will fix the errors. But let's confirm if we want to enable this feature.

image

**Comment by keithmattix** [comment]
To clarify, I'm not suggesting you fix the capitalization. I think the linting errors are safe to ignore for now as well

**Review by trstringer — APPROVED** [review]

**Pull request merged**
