### PR TITLE
Adding priorityClassName to the OSM deployments

### PR DESCRIPTION
**Pull request by draychev**
This PR adds `priorityClassName: system-node-critical` to the Open Service Mesh pods (controller and injector).

The purpose of this change is to ensure that the OSM pods are put in the highest priority class and evictions are prevented.  In recent testing with large clusters we are noticing OSM Controller and Injector pods being evicted. If the OSM Controller or Injector pods are evicted from a cluster, the service mesh will no longer operate correctly.

Tests performed:
- Added `PriorityClass` and `priorityClassName` to the OSM Controller pod spec within the OSS software.
- Ran the project on a busy cluster using `./demo/run-osm-demo.sh` 

Script to install OSM: https://gist.github.com/draychev/a6cf66becd1c05d0314f94b73e67180c
Script to install Demo: https://gist.github.com/draychev/2856ff210a7a41a255ff5169d150f77b

### CODE REVIEW

**Comment by allenlsy** [comment]
Did we see OSM pods evicted after low priority pods?

**Review by shashankram — COMMENTED** [review]
I am guessing this needs to be done for all OSM control plane components?

**Comment by draychev** [comment]
> Did we see OSM pods evicted after low priority pods?

@allenlsy After I added `priorityClass: system-node-critical` I stopped seeing evictions.

**Comment by snehachhabria** [comment]
code has been checked in with this PR : https://github.com/openservicemesh/osm/pull/4205

**Pull request closed without merging**
