### PR TITLE
Fixing links

### PR DESCRIPTION
**Pull request by bridgetkromhout**
Fixes https://github.com/openservicemesh/osm/issues/2451

Signed-off-by: Bridget Kromhout <bridget@kromhout.org>

### CODE REVIEW

**Review by shashankram — APPROVED** [review]
Thanks!

**Comment by bridgetkromhout** [comment]
The link still works in https://deploy-preview-2739--osm-docs.netlify.app/docs/troubleshooting/uninstall/ but is still not right in github (https://github.com/bridgetkromhout/osm/blob/install-links/docs/content/docs/troubleshooting/uninstall.md). Checking my work to see where I missed the extra "docs". 

(This is what I'm talking about when I say this is unsustainable...)

**Comment by shashankram** [comment]
> The link still works in https://deploy-preview-2739--osm-docs.netlify.app/docs/troubleshooting/uninstall/ but is still not right in github (https://github.com/bridgetkromhout/osm/blob/install-links/docs/content/docs/troubleshooting/uninstall.md). Checking my work to see where I missed the extra "docs".
> 
> (This is what I'm talking about when I say this is unsustainable...)

@bridgetkromhout this definitely seems unsustainable, might as well prioritize just the website and have clear guidelines for those.

**Comment by bridgetkromhout** [comment]
> @bridgetkromhout this definitely seems unsustainable, might as well prioritize just the website and have clear guidelines for those.

I fixed this specific case and yeah... this is not going to work long-term. It's hard to get right even when I know exactly what I need to do. Casual contributors are going to break either the website, the github view, or both.

**Comment by bridgetkromhout** [comment]
And for the record, this is what I needed to fix:

`...content/docs/troubleshooting/uninstall.md → .../docs/troubleshooting/uninstall/_index.md `

Files that are attempting to link to other files need to have the expected directory depth, and this hack is how we reconcile the differences between how the website and github handle it.

**Comment by bridgetkromhout** [comment]
Link still works in https://deploy-preview-2739--osm-docs.netlify.app/docs/troubleshooting/uninstall/ and now also works in https://github.com/bridgetkromhout/osm/blob/install-links/docs/content/docs/troubleshooting/uninstall/_index.md.

**Review by michelleN — APPROVED** [review]

**Pull request merged**
