### PR TITLE
envoy/ads: program upsteam's service cert when making all secrets

### PR DESCRIPTION
**Pull request by shashankram**
**Description**:
There is a bug where the upstream service's service cert that
is referenced in the corresponding inbound filter chain for
the service is not programmed when there is a request to push
all secrets via XDS. Without this, it has been observed that
in certain environments the secrets often don't transition
from warming to active. As a result, mTLS is broken when
such a situation occurs.

This change programs the upsteam service's service cert
as a part of the request to provision all secrets associated
with the proxy.

This change does not address other potential XDS problems,
such as the one pertaining to XDS DiscoveryRequest with
an empty TypeUrl.

Potentially addresses #2749

Signed-off-by: Shashank Ram <shashr2204@gmail.com>

**Affected area**:

- New Functionality      [ ]
- Documentation          [ ]
- Install                [ ]
- Control Plane          [X]
- CLI Tool               [ ]
- Certificate Management [ ]
- Networking             [ ]
- Metrics                [ ]
- SMI Policy             [ ]
- Security               [ ]
- Tests                  [ ]
- CI System              [ ]
- Demo                   [ ]
- Performance            [ ]
- Other                  [ ]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?
`No`

### CODE REVIEW

**Review by draychev — APPROVED** [review]
Thanks for fixing this!

**Review by eduser25 — APPROVED** [review]

**Comment by draychev** [comment]
Even with this patch I still see `dynamic_warming_secrets`. I suspect the bug-hunt will have to continue 🥴

**Comment by eduser25** [comment]
> Even with this patch I still see `dynamic_warming_secrets`. I suspect the bug-hunt will have to continue 🥴

was this with the revert of sds indefinite timeout?
as long as we can repro...

**Comment by shashankram** [comment]
> > Even with this patch I still see `dynamic_warming_secrets`. I suspect the bug-hunt will have to continue 🥴
> 
> was this with the revert of sds indefinite timeout?
> as long as we can repro...

@draychev did you test this patch on the HEAD of `main`? Like @eduser25 pointed out, we need the SDS timeout revert + this change together. So far I couldn't reproduce the secrets being stuck in warming phase with this patch, but will continue to try to do so.

I believe we need to additionally address the following:
1. Handle empty TypeUrls in the discovery request -- @eduser25 was testing this
2. Instead of checking the request version to reject stale requests, check against the last sent nonce
3. Revisit XDS state machine and check for further correctness

**Pull request merged**
