### PR TITLE
fix(control-plane):  fix the context in the StreamAggregatedResources

### PR DESCRIPTION
**Pull request by storyicon**
Signed-off-by: storyicon <storyicon@foxmail.com>

**Description**:
I think there may be some clerical errors here, we should make the context meaningful.

**Affected area**:

- New Functionality      [ ]
- Documentation          [ ]
- Install                [ ]
- Control Plane          [ X ]
- CLI Tool               [ ]
- Certificate Management [ ]
- Networking             [ ]
- Metrics                [ ]
- SMI Policy             [ ]
- Security               [ ]
- Tests                  [ ]
- CI System              [ ]
- Demo                   [ ]
- Performance            [ ]
- Other                  [ ]

Please answer the following questions with yes/no.

- Does this change contain code from or inspired by another project? If so, did you notify the maintainers and provide attribution?

### CODE REVIEW

**Review by draychev — APPROVED** [review]
Thank you @storyicon

**Comment by shashankram** [comment]
Hey @storyicon, thanks for the change. Would you mind updating the commit message with more details as described in https://github.com/openservicemesh/osm/blob/main/CONTRIBUTING.md#commit-style-guideline.

**Review by eduser25 — APPROVED** [review]
I'll be keeping an eye on the pipelines for changes

**Comment by storyicon** [comment]
> Hey @storyicon, thanks for the change. Would you mind updating the commit message with more details as described in https://github.com/openservicemesh/osm/blob/main/CONTRIBUTING.md#commit-style-guideline.

@shashankram @eduser25  I tried to modify the commit message according to the guidelines, which is indeed a lot clearer. If you need me to make more changes, please contact me.

**Comment by shashankram** [comment]
> > Hey @storyicon, thanks for the change. Would you mind updating the commit message with more details as described in https://github.com/openservicemesh/osm/blob/main/CONTRIBUTING.md#commit-style-guideline.
> 
> @shashankram @eduser25 I tried to modify the commit message according to the guidelines, which is indeed a lot clearer. If you need me to make more changes, please contact me.

Hey @storyicon, thanks for updating the title, would you mind adding a short description to the commit to help folks to review. I understand the change, but it might not be obvious to some wondering the implications of this change.

**Pull request merged**
