### PR TITLE
ref(demo): update USE_PRIVATE_REGISTRY to false

### PR DESCRIPTION
**Pull request by michelleN**
The environment variable should be false by default as stated in the .env.example file. This PR changes the env default to false in the demo script to match.

Signed-off-by: Michelle Noorali <minooral@microsoft.com>

Please mark with X for applicable areas.

-->
**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [ ] |
| Documentation              | [ ] |
| Install                    | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [ ] |
| Ingress                    | [ ] |
| Egress                     | [ ] |
| Networking                 | [ ] |
| Observability              | [ ] |
| SMI Policy                 | [ ] |
| Sidecar Injection          | [ ] |
| Security                   | [ ] |
| Upgrade                    | [ ] |
| Tests                      | [ ] |
| CI System                  | [ ] |
| Demo                       | [ X] |
| Performance                | [ ] |
| Other                      | [ ] |

**Testing done**:
These changes were tested by running the demo successfully using a public docker registry where the container images were hosted.

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project? No
    -   Did you notify the maintainers and provide attribution? NA

2. Is this a breaking change? No

### CODE REVIEW

**Review by shashankram — CHANGES_REQUESTED** [review]
This script is predominantly used with a private registry for testing, so it makes sense to keep it as is. It's possible https://github.com/openservicemesh/osm/pull/3936 did not update the `.env.example` to reflect the change. Was there a reason for this change other than the comments in `.env.example` not matching?

**Comment by SanyaKochhar** [comment]
@nshankar13

**Comment by nshankar13** [comment]
@shashankram @michelleN the default value for USE_PRIVATE_REGISTRY was initially set to true, but we decided to change it to false since people would likely use private registries primarily used for testing. For the CI we override the default and set this to false since it uses kind, but in most other scenarios we probably want to keep it as true.

**Comment by nshankar13** [comment]
Also the .env.example now sets it as true: https://github.com/openservicemesh/osm/blob/main/.env.example#L176

**Comment by michelleN** [comment]
Thanks @nshankar13 and @shashankram. Closing this PR since I have more clarity now!

**Pull request closed without merging**
