### PR TITLE
release: Update versions to 0.9.0

### PR DESCRIPTION
**Pull request by ksubrmnn**
Signed-off-by: Kalya Subramanian <kasubra@microsoft.com>

**Description**:
Update osm version to 0.9.0

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [ ] |
| Documentation              | [X] |
| Install                    | [ ] |
| CLI Tool                   | [ ] |
| Certificate Management     | [ ] |
| Control Plane              | [ ] |
| Ingress                    | [ ] |
| Egress                     | [ ] |
| Networking                 | [ ] |
| Observability              | [ ] |
| SMI Policy                 | [ ] |
| Sidecar Injection          | [ ] |
| Security                   | [ ] |
| Upgrade                    | [ ] |
| Tests                      | [ ] |
| CI System                  | [ ] |
| Demo                       | [ ] |
| Performance                | [ ] |
| Other                      | [ ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project?
    -   Did you notify the maintainers and provide attribution?
No
1. Is this a breaking change?
No

### CODE REVIEW

**Review by allenlsy — APPROVED** [review]

**Review by nshankar13 — APPROVED** [review]

**Review by shashankram — CHANGES_REQUESTED** [review]
PR should be not created on the main repo branch.

**Comment by nojnhuh** [comment]
@shashankram The release branch has already been updated (#3589), but yes, it would be good to hold off on merging this until the v0.9.0 docker images this references have been published.

**Comment by shashankram** [comment]
> @shashankram The release branch has already been updated (#3589), but yes, it would be good to hold off on merging this until the v0.9.0 docker images this references have been published.

I am suggesting to create a cherry-pick from release-v0.9 to main for this either directly using github or manually through a PR created from a fork.

**Comment by nojnhuh** [comment]
Oh, I see what you mean now. I'm not sure it's worth recreating this PR from a branch of a fork. If the branch gets deleted right after this PR is merged, does it make a difference?

**Comment by ksubrmnn** [comment]
Closed in favor of #3592

**Pull request closed without merging**
