### PR TITLE
catalog: Exporting errors so these are available outside pkg/catalog as well

### PR DESCRIPTION
**Pull request by draychev**
This PR renames (capitalizes) the errors in `pkg/catalog`

Exporting the `pkg/catalog` errors makes it possible for users of `catalog` to understand what went wrong (coming in PR https://github.com/openservicemesh/osm/pull/2625).

No functional code changes in this PR.

### CODE REVIEW

**Review by snehachhabria — APPROVED** [review]
Is there a plan to use these errors outside of catalog ?

**Comment by draychev** [comment]
@snehachhabria 
> Is there a plan to use these errors outside of catalog ?

Yes - starting w/ this test:  https://github.com/openservicemesh/osm/pull/2625   (which I'll resurrect shortly)

**Review by shashankram — APPROVED** [review]
I'd really like to see the change that require these variable to be exported in the same PR that exports the variable, just so we don't have variables that don't need to be exported being exported later on.

These changes are small enough to be in the same PR that requires them to be exported.

**Comment by draychev** [comment]
@shashankram Here is one example where the `catalog` error makes sense to be bubbled up (instead of rewriting it): https://github.com/openservicemesh/osm/pull/2627/files#diff-7a1f450fbabb0088828083ed90ad3ccc49ed4edd9ae6f58ad5bdcdd158b2dda8R141

And run tests against these error conditions: https://github.com/openservicemesh/osm/pull/2627/files#diff-f4d146b2f432d283619be84d448017b08e2dafd4a489ddf306d629f48d6f5366R214-R217

**Comment by shashankram** [comment]
> @shashankram Here is one example where the `catalog` error makes sense to be bubbled up (instead of rewriting it): https://github.com/openservicemesh/osm/pull/2627/files#diff-7a1f450fbabb0088828083ed90ad3ccc49ed4edd9ae6f58ad5bdcdd158b2dda8R141
> 
> And run tests against these error conditions: https://github.com/openservicemesh/osm/pull/2627/files#diff-f4d146b2f432d283619be84d448017b08e2dafd4a489ddf306d629f48d6f5366R214-R217

Good stuff! I guess we should always export errors being returned across package boundaries?

**Pull request merged**
