### PR TITLE
egress: enable egress policy by default

### PR DESCRIPTION
**Pull request by shashankram**
**Description**:
Enables egress policy by default.

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| Install                    | [X] |
| Egress                     | [X] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project? `no`
    -   Did you notify the maintainers and provide attribution?

1. Is this a breaking change? `no`

### CODE REVIEW

**Review by snehachhabria — APPROVED** [review]
If tis is going to be enabled by default, will we still need the feature flag ?

**Comment by shashankram** [comment]
> If tis is going to be enabled by default, will we still need the feature flag ?

I left this because it gives us the option to quickly disable it if there are any regressions from enabling it by default. We can deprecate the feature flag in the next release.

**Review by shalier — APPROVED** [review]

**Comment by shashankram** [comment]
@Mergifyio backport release-v0.8

**Comment by shashankram** [comment]
> @Mergifyio backport release-v0.8

@Mergifyio backport release-v0.9

**Comment by shashankram** [comment]
@Mergifyio backport release-v0.9

**Pull request merged**
