### PR TITLE
Appended version check

### PR DESCRIPTION
**Pull request by mudit-01**
Now OSM CLI version check will happen regardless of any K8s cluster

Signed-off-by: mudit singh <mudit.singh@india.nec.com>

**Description**: Earlier the OSM CLI version check only happened when there is K8s cluster present as below
ss1
If no K8s cluster is present below is the output
ss2

**Testing done**: Yes Manual testing done below are the screenshots
With K8s cluster
ss3

Without K8s cluster
ss4

**Affected area**:
| Functional Area            |     |
| -------------------------- | --- |
| New Functionality          | [ ] |
| CI System                  | [ ] |
| CLI Tool                   | [ X] |
| Certificate Management     | [ ] |
| Control Plane              | [ ] |
| Demo                       | [ ] |
| Documentation              | [ ] |
| Egress                     | [ ] |
| Ingress                    | [ ] |
| Install                    | [ ] |
| Networking                 | [ ] |
| Observability              | [ ] |
| Performance                | [ ] |
| SMI Policy                 | [ ] |
| Security                   | [ ] |
| Sidecar Injection          | [ ] |
| Tests                      | [ ] |
| Upgrade                    | [ ] |
| Other                      | [ ] |

Please answer the following questions with yes/no.

1. Does this change contain code from or inspired by another project?
    -   Did you notify the maintainers and provide attribution?
No
2. Is this a breaking change?
No
3. Has documentation corresponding to this change been updated in the [osm-docs](https://github.com/openservicemesh/osm-docs) repo (if applicable)?

### CODE REVIEW

**Comment by mudit-01** [comment]
@keithmattix @shalier @jaellio @steeling go mock test is taking too much time PTAL thanks

**Comment by jaellio** [comment]
Hi @mudit-01, thanks for the PR! 

In the following image, I believe the reason the latest available version information isn't displaying is that at that time v1.2.2 (the CLI version in your image) was the latest version.
image

If you perform the same command with version v1.2.1 of the CLI and no cluster I believe the latest available version will be outputted. If this is the case, I don't think it is necessary to move the logic to output the latest available version information.

Let me know if you have any questions!

**Review by jaellio — CHANGES_REQUESTED** [review]
Hi @mudit-01, thanks for the PR!

In the following example, I believe the latest version information wasn't outputted because at that time v1.2.2 (the CLI version in the example) was the latest version.
image

If you try the same command without a configured cluster with version v1.2.1 of the OSM CLI I believe you will see the latest version output. If this is the case, I don't think it is necessary to move the logic for outputting the latest version. 

Let me know if you have any questions!

**Comment by mudit-01** [comment]
Thanks, @jaellio for the comment, I tried with v1.2.1 but it did not show the new version 
cli

Even with OSM CLI v1.2.2 it do not show latest v1.2.3 available.
cli2

By moving logic it can output the desired new version
cli3

**Comment by mudit-01** [comment]
@jaellio PTAL

**Review by jaellio — APPROVED** [review]

**Comment by jaellio** [comment]
> Thanks, @jaellio for the comment, I tried with v1.2.1 but it did not show the new version cli
> 
> Even with OSM CLI v1.2.2 it do not show latest v1.2.3 available. cli2
> 
> By moving logic it can output the desired new version cli3

Yes, you're correct! I missed the return statement on [line 79](https://github.com/openservicemesh/osm/pull/5266/files#diff-f28cb61ea320d1d240ba694ffd62cdc96737ea02ad06bd64425a16329d3fcdb7L79). 

LGTM

**Review by keithmattix — APPROVED** [review]

**Comment by mudit-01** [comment]
Thanks! @keithmattix for the review.

**Comment by mudit-01** [comment]
@jaellio @keithmattix we can merge this?

**Comment by mudit-01** [comment]
Thanks! @jaellio

**Pull request merged**
